/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboard': typeof OnboardRoute
  '/requests': typeof RequestsRoute
  '/reset': typeof ResetRoute
  '/schedule': typeof ScheduleRoute
  '/setup': typeof SetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboard': typeof OnboardRoute
  '/requests': typeof RequestsRoute
  '/reset': typeof ResetRoute
  '/schedule': typeof ScheduleRoute
  '/setup': typeof SetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ask': typeof AskRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/home': typeof HomeRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboard': typeof OnboardRoute
  '/requests': typeof RequestsRoute
  '/reset': typeof ResetRoute
  '/schedule': typeof ScheduleRoute
  '/setup': typeof SetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ask'
    | '/calendar'
    | '/dashboard'
    | '/forgot'
    | '/home'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/me'
    | '/onboard'
    | '/requests'
    | '/reset'
    | '/schedule'
    | '/setup'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ask'
    | '/calendar'
    | '/dashboard'
    | '/forgot'
    | '/home'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/me'
    | '/onboard'
    | '/requests'
    | '/reset'
    | '/schedule'
    | '/setup'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ask'
    | '/calendar'
    | '/dashboard'
    | '/forgot'
    | '/home'
    | '/privacy'
    | '/terms'
    | '/login'
    | '/me'
    | '/onboard'
    | '/requests'
    | '/reset'
    | '/schedule'
    | '/setup'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AskRoute: typeof AskRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ForgotRoute: typeof ForgotRoute
  HomeRoute: typeof HomeRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  OnboardRoute: typeof OnboardRoute
  RequestsRoute: typeof RequestsRoute
  ResetRoute: typeof ResetRoute
  ScheduleRoute: typeof ScheduleRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AskRoute: AskRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ForgotRoute: ForgotRoute,
  HomeRoute: HomeRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  OnboardRoute: OnboardRoute,
  RequestsRoute: RequestsRoute,
  ResetRoute: ResetRoute,
  ScheduleRoute: ScheduleRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
